:recycle: Condense status check logs
kids-first/kf-api-study-creator pull request #630
Opened 2021-04-23 21:59 UTC by gsantia

Closes #603.

Refactors the task decorator logs to be less repetitive.

2021-04-23 22:23 UTC, gsantia commented
codecov failed??? All I changed was the logging...

2021-04-26 13:47 UTC, znatty22 requested changes
Btw, codecov was always failing for job logs stuff. Your code changes didn't change the previous code cov which is confirmed by the codecov diff status check passing.

2021-04-26 13:47 UTC, znatty22 commented on creator/decorators.py
> +        self.logger.info(f"Job complete after {duration:.2f}s. 👋")
I liked part that logged the ID of the job log. Can we add that into this line or make a new line for it?

2021-04-26 14:07 UTC, dankolbman approved these changes
# :boat:

2021-04-28 19:33 UTC, dankolbman approved these changes
# :cake:

2021-04-28 20:56 UTC, znatty22 approved these changes
☀️

2021-04-28 21:11 UTC, merged