Add mutations to add or remove templates to/from studies
kids-first/kf-api-study-creator pull request #693
Opened 2021-07-08 15:57 UTC by gsantia

Closes #676

2021-07-16 15:52 UTC, dankolbman approved these changes
# 🤺

2021-07-16 17:34 UTC, znatty22 requested changes
Files are getting kinda large 😬. Could you separate out this functionality into something like this:

`creator/data_templates/mutations/study_templates.py`
`tests/data_templates/test_study_template_mutations.py`

2021-07-19 21:34 UTC, gsantia commented
Changes made to lower file sizes and to reflect changes on master

2021-07-19 21:34 UTC, gsantia commented
Changes made to lower file sizes and to reflect changes on master

2021-07-20 16:10 UTC, dankolbman approved these changes
# 🪛

2021-07-20 19:30 UTC, znatty22 approved these changes
Thanks gio!

2021-07-20 20:02 UTC, merged